name = "Julia Code Server"
version = "0.1.0"
authors = ["Rodrigo Zepeda-Tello <rzepeda17@gmail.com>"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"

[compat]
julia = "1"